replicaCount: 1

image:
  tag: develop-07859a8

ingress:
  host: portfolio-api-test.jcrlabs.net

resources:
  requests:
    cpu: 25m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi

hpa:
  minReplicas: 1
  maxReplicas: 2
